int numberA = 3;
int numberB = 5;
Console.WriteLine(numberA + numberB);
Console.WriteLine();
int number1 = 25;
int number2 = 31;
int result = number1 + number2;
Console.WriteLine(result);
Console.WriteLine();
int numberC = new Random().Next(1, 10);
int numberD = new Random().Next(1, 10);
Console.WriteLine(numberC);
Console.WriteLine(numberD);
Console.WriteLine(numberC + numberD);
